import sun from "./sun.png"
import ocean from "./ocean.png"
import c from "./icons8-c-48.png"
import cplus from "./icons8-c-48 (1).png"
import github from "./icons8-github-48.png"
import gcp from "./icons8-google-cloud-48.png"
import mysql from "./icons8-mysql-48.png"
import python from "./icons8-python-48.png"
import react from "./icons8-react-48.png"
import typescript from "./icons8-typescript-48.png"
import instagram from "./icons8-instagram-96.png"
import linkedin from "./icons8-linkedin-96.png"
import githubsocial from "./icons8-github-96.png"
import moon from "./moon.png"
import cloud from "./clouds.png"
import link from "./icons8-link-96.png"
import cinflix from "./cinflix.jpg"
import magiccards from "./ma.jpg"
import algorithmvisual from "./algo_visual.jpg"
import quiz from "./quiz.jpg"
import mespace from "./me_space.png"
export {sun,ocean,cplus,c,github,gcp,mysql,python,react,typescript,githubsocial,linkedin,instagram,cloud,moon, link,cinflix,magiccards,quiz,algorithmvisual,mespace}